# Generated by Django 3.0 on 2019-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill',
            field=models.CharField(choices=[('BAT', 'BATSMAN'), ('BOW', 'BLOWLER'), ('WCK', 'WICKETKEEPER'), ('ALL', 'ALLROUNDER')], default='Batsmen', max_length=100),
        ),
    ]
