# Generated by Django 3.0 on 2019-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jerseyno',
            field=models.IntegerField(),
        ),
    ]
