# Generated by Django 3.0 on 2019-12-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'NOT STARTED'), ('R', 'ON GOING'), ('C', 'FINISHED'), ('A', 'ABANDONED')], max_length=1)),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_first_team', to='teams.Team')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_second_team', to='teams.Team')),
            ],
        ),
    ]
