# Generated by Django 3.0 on 2019-12-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('NOT STARTED', 'FIXTURE'), ('ON GOING', 'IN PROGRESS'), ('FINISHED', 'COMPLETED'), ('ABANDONED', 'ABANDONED'), ('Team Australia', 'Team Australia Won'), ('Team India', 'Team India Won'), ('Team Pakistan', 'Team Pakistan Won'), ('Team South Africa', 'Team South Africa Won'), ('Team Srilanka', 'Team Srilanka Won'), ('Team WestIndies', 'Team WestIndies Won'), ('Team England', 'Team England Won')], max_length=100),
        ),
    ]
