# Generated by Django 3.0 on 2019-12-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0002_auto_20191215_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='match_first_team', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='match_second_team', to='teams.Team'),
        ),
    ]
